export interface Hotel {
  id: number;
  name: string;
  nameEn: string;
  city: string;
  country: string;
  image: string;
  images: string[];
  rating: number;
  reviewCount: number;
  price: number;
  originalPrice?: number;
  stars: number;
  address: string;
  description: string;
  amenities: string[];
  tags: string[];
  type: "luxury" | "boutique" | "resort" | "budget" | "business";
  distance: string;
  featured: boolean;
  discount?: number;
}

export const mockHotels: Hotel[] = [
  // ===== 东京 =====
  {
    id: 1,
    name: "东京京王广场大酒店",
    nameEn: "Keio Plaza Hotel Tokyo",
    city: "东京",
    country: "日本",
    image: "/hotel/pexels-emilio-garcia-96280844-22922098.jpg",
    images: [],
    rating: 4.8,
    reviewCount: 3256,
    price: 1680,
    originalPrice: 2100,
    stars: 5,
    address: "2-2-1 Nishi-Shinjuku, Shinjuku-ku, Tokyo",
    description: "位于新宿核心地段，步行5分钟即达都厅。可俯瞰东京天际线，顶楼设有空中酒廊。",
    amenities: ["免费WiFi", "游泳池", "健身房", "餐厅", "机场接送", "商务中心", "SPA"],
    tags: ["商务", "观景", "新宿"],
    type: "luxury",
    distance: "距新宿站步行5分钟",
    featured: true,
    discount: 20,
  },
  {
    id: 2,
    name: "新宿灿路都广场大饭店",
    nameEn: "Hotel Sunroute Plaza Shinjuku",
    city: "东京",
    country: "日本",
    image: "/hotel/pexels-furkanakt-24800194.jpg",
    images: [],
    rating: 4.6,
    reviewCount: 2189,
    price: 890,
    originalPrice: 1100,
    stars: 4,
    address: "2-3-1 Yoyogi, Shibuya-ku, Tokyo",
    description: "紧邻新宿站南口，交通便利。房间虽精致但设施齐全，性价比极高的东京住宿选择。",
    amenities: ["免费WiFi", "餐厅", "洗衣服务", "行李寄存", "自动贩卖机"],
    tags: ["交通便利", "性价比", "新宿"],
    type: "business",
    distance: "距新宿站步行2分钟",
    featured: false,
    discount: 19,
  },
  {
    id: 3,
    name: "银座蒙特利酒店",
    nameEn: "Hotel Monterey Ginza",
    city: "东京",
    country: "日本",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80",
    images: [],
    rating: 4.5,
    reviewCount: 1523,
    price: 1280,
    stars: 4,
    address: "2-10-2 Ginza, Chuo-ku, Tokyo",
    description: "欧式古典风格设计，坐落于银座购物区中心。步行可达筑地市场，购物美食两不误。",
    amenities: ["免费WiFi", "餐厅", "洗衣服务", "叫醒服务", "前台保险箱"],
    tags: ["购物", "银座", "欧式"],
    type: "boutique",
    distance: "距银座站步行3分钟",
    featured: false,
  },

  // ===== 曼谷 =====
  {
    id: 4,
    name: "曼谷威客3號酒店",
    nameEn: "Vic3 Bangkok",
    city: "曼谷",
    country: "泰国",
    image: "/hotel/pexels-ana-hidalgo-burgos-4848204-33952744.jpg",
    images: [],
    rating: 4.5,
    reviewCount: 1876,
    price: 328,
    originalPrice: 450,
    stars: 3,
    address: "89 Phahon Yothin Soi 3, Phaya Thai, Bangkok",
    description: "设计感十足的青年旅舍风格酒店，临近BTS站。公共区域充满艺术气息，深受年轻旅行者喜爱。",
    amenities: ["免费WiFi", "游泳池", "餐厅", "共用厨房", "台球桌"],
    tags: ["设计感", "青年旅舍", "BTS"],
    type: "budget",
    distance: "距BTS Sanam Pao站步行3分钟",
    featured: true,
    discount: 27,
  },
  {
    id: 5,
    name: "曼谷半岛酒店",
    nameEn: "The Peninsula Bangkok",
    city: "曼谷",
    country: "泰国",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&q=80",
    images: [],
    rating: 4.9,
    reviewCount: 2876,
    price: 2580,
    stars: 5,
    address: "333 Charoennakorn Road, Klongsan, Bangkok",
    description: "湄南河畔的奢华地标，每间客房均可欣赏河景。管家服务、河畔下午茶、泰式SPA，极致体验。",
    amenities: ["免费WiFi", "游泳池", "健身房", "SPA", "管家服务", "河景", "直升机停机坪"],
    tags: ["奢华", "河景", "蜜月"],
    type: "luxury",
    distance: "距BTS Saphan Taksin站有接驳船",
    featured: true,
  },
  {
    id: 6,
    name: "曼谷暹罗凯宾斯基酒店",
    nameEn: "Siam Kempinski Hotel Bangkok",
    city: "曼谷",
    country: "泰国",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80",
    images: [],
    rating: 4.8,
    reviewCount: 2134,
    price: 1880,
    stars: 5,
    address: "991/9 Rama I Road, Pathumwan, Bangkok",
    description: "直通Siam Paragon购物中心，被热带花园泳池环绕的城市绿洲。位置无可挑剔。",
    amenities: ["免费WiFi", "游泳池", "健身房", "SPA", "儿童俱乐部", "直通商场"],
    tags: ["购物", "亲子", "商务"],
    type: "luxury",
    distance: "直通Siam Paragon商场",
    featured: false,
  },

  // ===== 首尔 =====
  {
    id: 7,
    name: "天空花园酒店东大门1号店",
    nameEn: "Hotel Skypark Dongdaemun I",
    city: "首尔",
    country: "韩国",
    image: "/hotel/pexels-navlakha-32671528.jpg",
    images: [],
    rating: 4.4,
    reviewCount: 1654,
    price: 456,
    originalPrice: 580,
    stars: 3,
    address: "335 Dongho-ro, Jung-gu, Seoul",
    description: "东大门商圈核心位置，下楼就是购物天堂。屋顶露台可远眺首尔塔夜景。",
    amenities: ["免费WiFi", "屋顶露台", "行李寄存", "货币兑换"],
    tags: ["东大门", "购物", "夜景"],
    type: "budget",
    distance: "距东大门站步行3分钟",
    featured: false,
    discount: 21,
  },
  {
    id: 8,
    name: "首尔四季酒店",
    nameEn: "Four Seasons Hotel Seoul",
    city: "首尔",
    country: "韩国",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=600&q=80",
    images: [],
    rating: 4.9,
    reviewCount: 1456,
    price: 3200,
    stars: 5,
    address: "97 Saemunan-ro, Jongno-gu, Seoul",
    description: "光化门旁的现代宫殿，融合韩式美学与国际奢华。米其林餐厅、室内高尔夫、韩式SPA。",
    amenities: ["免费WiFi", "游泳池", "健身房", "SPA", "米其林餐厅", "室内高尔夫", "管家服务"],
    tags: ["奢华", "韩式", "商务"],
    type: "luxury",
    distance: "距光化门站步行2分钟",
    featured: false,
  },

  // ===== 巴厘岛 =====
  {
    id: 9,
    name: "阿雅娜度假村",
    nameEn: "AYANA Resort Bali",
    city: "巴厘岛",
    country: "印度尼西亚",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80",
    images: [],
    rating: 4.8,
    reviewCount: 4532,
    price: 2280,
    stars: 5,
    address: "Jl. Karang Mas Sejahtera, Jimbaran, Bali",
    description: "金巴兰湾悬崖之上的度假天堂，Rock Bar日落、私人海滩、12座泳池——一生必住一次的酒店。",
    amenities: ["免费WiFi", "私人海滩", "12座泳池", "Rock Bar", "SPA", "网球场", "高尔夫"],
    tags: ["度假", "蜜月", "悬崖"],
    type: "resort",
    distance: "距金巴兰海滩步行10分钟",
    featured: true,
  },
  {
    id: 10,
    name: "乌布空中花园酒店",
    nameEn: "Hanging Gardens of Bali",
    city: "巴厘岛",
    country: "印度尼西亚",
    image: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=600&q=80",
    images: [],
    rating: 4.7,
    reviewCount: 2341,
    price: 3580,
    stars: 5,
    address: "Desa Buahan, Payangan, Ubud, Bali",
    description: "丛林深处的隐世秘境，双层无边际泳池如悬于雨林之上。曾获评'全球最美泳池'。",
    amenities: ["免费WiFi", "无边际泳池", "SPA", "瑜伽", "丛林徒步", "有机餐厅"],
    tags: ["丛林", "蜜月", "泳池"],
    type: "resort",
    distance: "距乌布中心车程20分钟",
    featured: true,
  },

  // ===== 巴黎 =====
  {
    id: 11,
    name: "巴黎香格里拉酒店",
    nameEn: "Shangri-La Hotel Paris",
    city: "巴黎",
    country: "法国",
    image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600&q=80",
    images: [],
    rating: 4.8,
    reviewCount: 1876,
    price: 4500,
    stars: 5,
    address: "10 Avenue d'Iéna, 16th arr., Paris",
    description: "曾是拿破仑侄孙的宫殿，推窗即见埃菲尔铁塔。法式宫殿与亚洲待客之道的完美融合。",
    amenities: ["免费WiFi", "游泳池", "SPA", "米其林餐厅", "管家服务", "埃菲尔塔景"],
    tags: ["奢华", "宫殿", "埃菲尔"],
    type: "luxury",
    distance: "距埃菲尔铁塔步行15分钟",
    featured: true,
  },
  {
    id: 12,
    name: "巴黎茉黎斯酒店",
    nameEn: "Le Meurice Paris",
    city: "巴黎",
    country: "法国",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc0?w=600&q=80",
    images: [],
    rating: 4.7,
    reviewCount: 1234,
    price: 3800,
    stars: 5,
    address: "228 Rue de Rivoli, 1st arr., Paris",
    description: "达利最爱的酒店，面朝杜乐丽花园。洛可可风格的华丽内饰，米其林三星主厨坐镇。",
    amenities: ["免费WiFi", "SPA", "米其林三星", "管家服务", "花园景", "代客泊车"],
    tags: ["艺术", "奢华", "米其林"],
    type: "luxury",
    distance: "距卢浮宫步行5分钟",
    featured: false,
  },

  // ===== 国内精选 =====
  {
    id: 13,
    name: "北京王府半岛酒店",
    nameEn: "The Peninsula Beijing",
    city: "北京",
    country: "中国",
    image: "https://images.unsplash.com/photo-1591088398332-8a7791972843?w=600&q=80",
    images: [],
    rating: 4.8,
    reviewCount: 2134,
    price: 2200,
    stars: 5,
    address: "北京市东城区王府井金鱼胡同8号",
    description: "王府井核心地段，全套房式设计。融合中式传统与现代科技，半岛学堂带你体验京城文化。",
    amenities: ["免费WiFi", "游泳池", "SPA", "健身房", "半岛学堂", "劳斯莱斯接送"],
    tags: ["奢华", "王府井", "中式"],
    type: "luxury",
    distance: "距王府井步行街步行3分钟",
    featured: true,
  },
  {
    id: 14,
    name: "杭州法云安缦",
    nameEn: "Amanfayun Hangzhou",
    city: "杭州",
    country: "中国",
    image: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=600&q=80",
    images: [],
    rating: 4.9,
    reviewCount: 987,
    price: 5800,
    stars: 5,
    address: "杭州市西湖区法云弄22号",
    description: "隐于灵隐寺旁的古村落，47间院落由百年茶村改建。石径、竹林、禅意——顶级隐世体验。",
    amenities: ["免费WiFi", "SPA", "禅修", "茶道", "恒温泳池", "私人庭院"],
    tags: ["隐世", "禅意", "西湖"],
    type: "boutique",
    distance: "距灵隐寺步行5分钟",
    featured: false,
  },
  {
    id: 15,
    name: "上海外滩华尔道夫酒店",
    nameEn: "Waldorf Astoria Shanghai",
    city: "上海",
    country: "中国",
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80",
    images: [],
    rating: 4.8,
    reviewCount: 2567,
    price: 2600,
    stars: 5,
    address: "上海市黄浦区中山东一路2号",
    description: "外滩万国建筑群中的百年经典，新楼与老楼交相辉映。长廊酒吧的传奇鸡尾酒不容错过。",
    amenities: ["免费WiFi", "游泳池", "SPA", "米其林餐厅", "长廊酒吧", "江景"],
    tags: ["外滩", "经典", "江景"],
    type: "luxury",
    distance: "距南京路步行街步行5分钟",
    featured: true,
  },
  {
    id: 16,
    name: "成都博舍酒店",
    nameEn: "The Temple House Chengdu",
    city: "成都",
    country: "中国",
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&q=80",
    images: [],
    rating: 4.7,
    reviewCount: 1678,
    price: 1800,
    stars: 5,
    address: "成都市锦江区笔帖式街81号",
    description: "太古里旁的百年院落，现代设计与川西传统的精彩碰撞。井酒吧与谧寻茶室同样精彩。",
    amenities: ["免费WiFi", "游泳池", "健身房", "SPA", "酒吧", "茶室"],
    tags: ["设计感", "太古里", "川西"],
    type: "boutique",
    distance: "太古里步行2分钟",
    featured: false,
  },

  // ===== 更多国际 =====
  {
    id: 17,
    name: "滨海湾金沙酒店",
    nameEn: "Marina Bay Sands Singapore",
    city: "新加坡",
    country: "新加坡",
    image: "https://images.unsplash.com/photo-1563911302283-d2bc129e7570?w=600&q=80",
    images: [],
    rating: 4.7,
    reviewCount: 18765,
    price: 2800,
    stars: 5,
    address: "10 Bayfront Avenue, Singapore",
    description: "新加坡地标——无边泳池横跨三座塔楼之巅。楼下即金沙购物城与赌场，极致体验。",
    amenities: ["免费WiFi", "无边泳池", "赌场", "购物中心", "空中花园", "剧院"],
    tags: ["地标", "无边泳池", "购物"],
    type: "luxury",
    distance: "距滨海湾花园步行10分钟",
    featured: false,
  },
  {
    id: 18,
    name: "纽约华尔道夫酒店",
    nameEn: "Waldorf Astoria New York",
    city: "纽约",
    country: "美国",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&q=80",
    images: [],
    rating: 4.6,
    reviewCount: 4567,
    price: 3500,
    stars: 5,
    address: "301 Park Avenue, New York, NY",
    description: "Park Avenue的Art Deco经典。历经翻新后重新定义奢华，每间套房均由名设计师打造。",
    amenities: ["免费WiFi", "SPA", "米其林餐厅", "管家服务", "代客泊车", "健身中心"],
    tags: ["经典", "Art Deco", "商务"],
    type: "luxury",
    distance: "距中央公园步行10分钟",
    featured: false,
  },
  {
    id: 19,
    name: "悉尼洲际酒店",
    nameEn: "InterContinental Sydney",
    city: "悉尼",
    country: "澳大利亚",
    image: "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?w=600&q=80",
    images: [],
    rating: 4.7,
    reviewCount: 2345,
    price: 2100,
    stars: 5,
    address: "117 Macquarie Street, Sydney",
    description: "历史建筑改建，坐拥环形码头全景。屋顶酒吧直面歌剧院与海港大桥，位置绝佳。",
    amenities: ["免费WiFi", "游泳池", "屋顶酒吧", "健身房", "歌剧院景", "商务中心"],
    tags: ["海港景", "歌剧院", "历史建筑"],
    type: "luxury",
    distance: "距歌剧院步行8分钟",
    featured: false,
  },
  {
    id: 20,
    name: "清迈四季酒店",
    nameEn: "Four Seasons Resort Chiang Mai",
    city: "清迈",
    country: "泰国",
    image: "https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=600&q=80",
    images: [],
    rating: 4.9,
    reviewCount: 1234,
    price: 3200,
    stars: 5,
    address: "Mae Rim-Samoeng Old Road, Chiang Mai",
    description: "湄林谷中的稻田秘境，在水稻田中做SPA、与大象互动。兰纳风格的亭阁别墅隐于热带花园。",
    amenities: ["免费WiFi", "游泳池", "SPA", "稻田体验", "大象互动", "烹饪课程", "瑜伽"],
    tags: ["稻田", "SPA", "亲子"],
    type: "resort",
    distance: "距清迈市区车程30分钟",
    featured: false,
  },
];

/** 酒店设施列表（用于筛选） */
export const amenityOptions = [
  "免费WiFi",
  "游泳池",
  "健身房",
  "SPA",
  "餐厅",
  "机场接送",
  "商务中心",
  "儿童俱乐部",
  "管家服务",
  "私人海滩",
  "停车",
  "宠物友好",
];

/** 酒店类型 */
export const typeOptions = [
  { value: "all", label: "全部类型" },
  { value: "luxury", label: "豪华酒店" },
  { value: "boutique", label: "精品酒店" },
  { value: "resort", label: "度假村" },
  { value: "business", label: "商务酒店" },
  { value: "budget", label: "经济型" },
];

/** 星级选项 */
export const starOptions = [
  { value: 5, label: "五星级" },
  { value: 4, label: "四星级" },
  { value: 3, label: "三星级" },
];

/** 城市选项 */
export const cityOptions = [
  { value: "all", label: "全部城市" },
  ...Array.from(new Set(mockHotels.map((h) => h.city))).map((city) => ({
    value: city,
    label: city,
  })),
];

/** 排序选项 */
export const sortOptions = [
  { value: "recommended", label: "推荐排序" },
  { value: "price-low", label: "价格从低到高" },
  { value: "price-high", label: "价格从高到低" },
  { value: "rating", label: "评分最高" },
  { value: "reviews", label: "评论最多" },
];
